<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cartproductreader"
 *
 * Auto generated by Extension Builder 2019-08-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cart product reader',
    'description' => 'Reads Excel file for inserting and updating products in cart_product.',
    'category' => 'module',
    'author' => 'Markus Puffer',
    'author_email' => 'm.puffer@pm-webdesign.eu',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
